### ISSUE TITLE
switching to the new unwind code

### ISSUE THREAD

**Issue by kachini** [HewlettPackard/LinuxKI#1]
Are there any plans to move to new unwind code? 
https://patchwork.kernel.org/patch/9334149/

Old unwind code is removed since ~4.9  and dump_trace() deprecated. So likit fails to compile with new kernels.

**Comment by MarkCRay** [comment]
Thanks for the feedback.   I had only tested it through 4.8.15, but my goal is to move it forward to new releases.   I'll take a look at this soon!

**Comment by MarkCRay** [comment]
This has been fixed in LinuxKI 5.3, which support linux kernels upto 4.12.8.
