### ISSUE TITLE
Missing files needed to create packages

### ISSUE THREAD

**Issue by cvoltz** [HewlettPackard/LinuxKI#10]
I forked the repository with the intent to fix issue #8 only to find that the ``.spec`` file is not included in the repository. I will generate a patch to ``scripts/linuxki_install`` to fix the problem but I believe that anything needed to create the RPM and DEB packages should be in the repository. Can you please add the missing ``.spec`` file and the files used to generate the scripts in the RPM to the repository?

**Comment by MarkCRay** [comment]
Presently, I don't have any plans to include scripts and the SPEC files to generate the RPM and DEB files.   You can always install from a branch or fork and can compile kiinfo and the likit.ko as needed for the specific systems you are working on.
