### ISSUE TITLE
Typo on runki

### ISSUE THREAD

**Issue by xguitian** [HewlettPackard/LinuxKI#15]
Hi!

I've notice a typo on runki shell script:
https://github.com/HewlettPackard/LinuxKI/blob/ce33fdfebd84ccd272bc98161869cedbfb4d9b3f/scripts/runki#L1139

There is a redirection to "/dev=null" instead on "/dev/null"

Thanks

**Comment by MarkCRay** [comment]
Thanks.   That's been there a long time, just never noticed it.   I'll get it fixed for the next release.

Mark

**Comment by MarkCRay** [comment]
Fixed in LinuxKI 5.6.
