### ISSUE TITLE
Creating visualizations takes an excessive amount of time

### ISSUE THREAD

**Issue by cvoltz** [HewlettPackard/LinuxKI#22]
When running `kiall -V`, it takes a long time to generate all of the visualization files when the capture is for a machine which had a lot of threads running on it (23,906 in my case). Running `kiall` without the `-V` took ~4 minutes. Running it with `-V` took ~35 minutes on a machine with 40 cores (E5-2650 @ 2.30 GHz), 64 GB of memory, and all the processing running on an SSD. One core runs at 100% but rest of the cores are essentially idle. Top reported 91.3% idle CPU time and 0 wait time. This looks like a classic case of single thread processing being the bottleneck. The output from `strace` shows that the process is creating a file in `PIDS`, then creating the `pid_detail.json` and `pid_wtree.json` in `VIS/<pid#>`, then closing all 3 files and moving onto the next PID. I haven't dug through the code to see what is going on but couldn't the processing be done in multiple threads (i.e., different threads working on generating different different JSON files) to reduce the time needed to generate the visualizations? Is there a fundamental reason why this can't be done (e.g., writing to data structures which aren't multi-thread safe)?

**Comment by MarkCRay** [comment]
With visualization, kiinfo does timeline processing for every 100 msecs of data.  So every 100 msecs of time, it must traverse through the entire PID list to print per-pid timeline information.     The kipid.*.txt data has all the PIDs and needs to be printed one PID at a time, but that's only done at the end.   I think I can use mutiple threads for the per-pid timeline processing to speed it up.   

I'll likely make this an optional parameter.  Some people may run kiall on their production system and I would not want to use too much CPU.   But for dedicated systems to read KI data (like I have), it could be very useful.     So definitely considering this.

**Comment by MarkCRay** [comment]
LinuxKI 6.0 introduces a multi-threaded version of kiinfo which can greatly reduce the Visualization processing used by kiall -V. When kiall -V is executing with the "-P [num_threads] option, kiinfo will create "num_threads" and perform parallel processing when generating the per-PID VIS reports. If the "-P" option is used and the number of threads is omitted or 0, then kiinfo will create one thread per logical core.   For example, the following will create one thread per logical core:

$ kiall -V -P

And the following will create 16 threads, or the maximum number of logical cores, whichever is smallest.

$ kiall -V -P 16

In internal tests, the new multi-threaded version reduced the processing time of kiall -V by factor of 2-10X, depending on the trace data collected.
