### ISSUE TITLE
ER: Add Read KB/sec and Write KB/sec to kidsk output

### ISSUE THREAD

**Issue by JanClaasSchreiber** [HewlettPackard/LinuxKI#23]
The kidsk.txt output currently looks as follows:
```
Top 20 Tasks sorted by Multipath I/O

     Cnt      r/s      w/s    KB/sec    Avserv      PID  Process
==============================================================================
   49534      137     2339  728569.2     1.935   223012  abc
```
Please enhance it so the **type** of the amount of data transfered by the threads can be identified:
```
Top 20 Tasks sorted by Multipath I/O

     Cnt       r/s   rAvserv     rKB/s      w/s   wAvserv   wKB/sec    Avserv      PID  Process
====================================================================================================
   49534       137     3.123    8569.0     2339     0.512  720000.2     1.935   223012  abc
```

**Comment by MarkCRay** [comment]
Fixed in LinuxKI version 6.0.

The totals are now printed following the devices in the same format as the device data.  For example:

    ******** DEVICE-MAPPER REPORT ********
        device   rw  avque avinflt   io/s   KB/s  avsz   avwait   avserv    tot    seq    rnd  reque  flush maxwait maxserv
    0x0fd00003   /dev/mapper/mpathb  ->  /dev/dm-3
      0x0fd00003  r   0.00    0.00      0      0     0     0.00     0.00      0      0      0      0      0     0.0     0.0
      0x0fd00003  w   0.50    0.25   1666  13324     8     0.00     0.22  33311      0  33311      0      0     0.0    46.1
      0x0fd00003  t   0.50    0.25   1666  13324     8     0.00     0.22  33311      0  33311      0      0     0.0    46.1

        device   rw  avque avinflt   io/s   KB/s  avsz   avwait   avserv    tot    seq    rnd  reque  flush maxwait maxserv
         All      r   0.00    0.00      0      0     0     0.00     0.00      0      0      0      0      0     0.0     0.0
         All      w   0.50    0.25   1666  13324     8     0.00     0.22  33311      0      0      0      0     0.0    46.1
         All      t   0.50    0.25   1666  13324     8     0.00     0.22  33311      0      0      0      0     0.0    46.1
