### ISSUE TITLE
Old files in repository

### ISSUE THREAD

**Issue by cvoltz** [HewlettPackard/LinuxKI#25]
Looks like there are a few files in the repository which don't belong there:

- `experimental/D3/lib/parcoord/.slickgrid.html.swp`
- `experimental/vis/cluster_timeline.html.orig`
- `experimental/vis/futex_scatter.html.rev2`
- `experimental/vis/kidsk_scatter.html.backup`
- `TaskletIRQs.htm`. This hasn't been updated since 5.6 while there is also `taskletIRQs.htm` which was updated recently. On a case insensitive system like Windows, you may only see one file but the repository has both. I suspect it was renamed but the old file didn't get deleted since the files are very similar. Two files differing only in case is a real problem for syncing solutions like Dropbox.
- `md_flush.htm`. This hasn't been updated since 5.4 while there is also the file 'mdflush.htm'. I suspect it was renamed but the old file didn't get deleted since the files are very similar.

**Comment by cvoltz** [comment]
Created #27.

**Comment by MarkCRay** [comment]
Fixed in LinuxKI version 6.0.
