### ISSUE TITLE
Generated HTML difficult to read in lynx

### ISSUE THREAD

**Issue by nfd9001** [HewlettPackard/LinuxKI#28]
After taking a short KI sample, I figured the easiest way to check if the generated file captured the data I wanted would be to pop open a textmode browser directly on the server and take a quick peek at the html output of `kiall -r`. Unfortunately, most of the result rows throughout the file sort of mushed together. This can imply other accessibility issues: if it doesn't look good in a textmode browser, it probably doesn't sound good to a screenreader!

This could probably be remedied reasonably well by just generating the results as properly-structured HTML tables.

**Comment by MarkCRay** [comment]
Thanks for the request.   I've never used a "text-based" web browser before, so I'll have to look into it.   However, if you prefer a test base report instead of HTML, you can execute kiall -r -x (or kiall -x if you have already done the kiall -r) and it will generate a text-base kp.*.txt file, which you can view with VI.

**Comment by nfd9001** [comment]
Thanks; I haven't checked out the plaintext version, but it seems pretty handy. It'd be nice for the direct links to more-detailed files, though, so it's probably worth bearing in mind.

I also tried opening a KI file in `links`, which flows the text in that file in a way that happens to be much easier to read than `lynx`. If you want to compare a few more, you could also check any of these: elinks, retawq, netrik, or w3m. You'll probably be able to find some of these on your plain ol' package manager repos, and you'll definitely be able to find lynx. Some of these will probably leave the page looking better than others, and a reasonable (weirdo) user like me will probably just pick one that makes the page look a bit better and be done with it.

None of that changes that it'll sound like absolute chaos to a screenreader. (As a fun exercise to anybody just scrolling through these issues in the future, you should totally try installing a screenreader popular with blind/low-vision users of your OS. Then, compare the experience of making sense of, say, the [Hacker News homepage](https://news.ycombinator.com) with a news article or a complicated web app like Slack or Discord. No peeking!) When you're thinking about HTML this way, the more you make your structure simple and explicit (rather than visual) the better. Some blind performance analyst will be thanking you later for your attention to detail. There are more blind developers out there than you might think 😁 

The meat of structuring those output data in HTML is the sort of thing I imagine could be mostly solved in a few lines of awk, and it'd probably kill n birds with n - k stones.

**Comment by MarkCRay** [comment]
Thanks for the feedback.  I'm a bit behind checking my gmail account.   All the HTML code is simply generated via printf statements in the code using macros.    See the html.h file in the source code for kiinfo.    So if I'm not printing the HTML out properly, then I'll have to fix it.

**Comment by MarkCRay** [comment]
I should have this fixed in the 6.1 version.    Hope to release by end of month.

**Comment by MarkCRay** [comment]
Fixed in 6.1 released on 04/19/2020
