### ISSUE TITLE
Feature request: add bash completion support

### ISSUE THREAD

**Issue by cvoltz** [HewlettPackard/LinuxKI#3]
Given the number of command line options supported by the various tools, it would be nice if the RPM install included a `bash` completion script.

Some useful references on how to create `bash` completion scripts are:
* [An introduction to bash completion: part 1](https://debian-administration.org/article/316/An_introduction_to_bash_completion_part_1)
* [An introduction to bash completion: part 2](https://debian-administration.org/article/317/An_introduction_to_bash_completion_part_2)
* [Bash Reference Manual Section 8.6: Programmable Completion](https://www.gnu.org/software/bash/manual/bash.html#Programmable-Completion)
* [Bash completion scripts git repository](https://anonscm.debian.org/gitweb/?p=bash-completion/bash-completion.git)

**Comment by MarkCRay** [comment]
Added bash completion for kiinfo command in LinuxKI 5.10.
