### ISSUE TITLE
Idea: use ebpf to replace liki.ko?

### ISSUE THREAD

**Issue by wenbinzeng** [HewlettPackard/LinuxKI#32]
Hi Mark,

I am wondering if it is possible to replace liki ko with ebpf on newer kernels? ebpf is supposed to be more native and robust than kernel modules, isn't it?

Best regards,
Wenbin

**Comment by kachini** [comment]
sooner or later we will need to move there. eBPF gives so many advantages, much more safe, easier to port to other platforms, kernels, etc.. 
it is hard to panic the box with eBPF.

**Comment by MarkCRay** [comment]
There's a couple of challenges/unknowns here.  First, can we use eBPF to get stack traces, which is one of the problem area.   The 2nd is performance.    We can dump a lot of unformatted data to the ring buffers very quickly and get those dumped to disk,.    We also have synchronized clocks to order trace events correctly between cores.    If we don't lose features like this, then its possible.

However, this would take some major rewrite.   Not sure when I'll have time.   It's opensource, so feel free to contribute.

**Comment by MarkCRay** [comment]
I'm going to close this out for now as I don't see re-writing LinuxKI at the present time to use eBPF.
