### ISSUE TITLE
linuxki traces from a core dump? 

### ISSUE THREAD

**Issue by kachini** [HewlettPackard/LinuxKI#35]
there was a nice functionality on HP-UX to extract some ki traces from a crash dump. Wondering if we could have something similar, like enable tracing and later dump traces from a core?

**Comment by MarkCRay** [comment]
The ftrace or kernel ring buffers may be available in a kernel crashdump, but it would take some effort to extract that data out and format it.     HP-UX KI used libp4 which make the dump analysis part fairly easy, but it would be much more difficult on Linux.   While this feature would have some benefits, there are no plans to do this in the near future.   However, it is opensource software, so you are welcome to contribute if you like.
