### ISSUE TITLE
Add "how to compile & install from source code" section in document

### ISSUE THREAD

**Issue by NanXiao** [HewlettPackard/LinuxKI#37]
Hi @MarkCRay and LinuxKI developers,

Greetings from me!

I checked both [README](https://github.com/HewlettPackard/LinuxKI/blob/master/README.md) and [LinuxKI_MasterClass](https://github.com/HewlettPackard/LinuxKI/blob/master/documentation/LinuxKI_MasterClass.pdf), and it seems that there lacks a section which introduces how to compile & install from source code. Is it possible to add this section in document? Thanks very much in advance!

Best Regards
Nan Xiao

**Comment by MarkCRay** [comment]
In the src/kiinfo and src/liki directories, there is a Makefile for both kiinfo and likit.ko.        Also, if you look at the LinuxKI FAQ, there is some documentation about the module_prep script.     Meanwhile, I'll add something to the LinuxKI Masterclass as well.
