### ISSUE TITLE
Any plan to support newest kernel?

### ISSUE THREAD

**Issue by NanXiao** [HewlettPackard/LinuxKI#38]
Hi @MarkCRay,

Greetings from me!

It seems `kallsyms_lookup_name()` and `kallsyms_on_each_symbol ()` are not exported any more in the newest kernel (from this [commit](https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=0bd476e6c67190b5eb7b6e105c8db8ff61103281)). So does `LinuxKI` have plan to support newest kernel? Thanks very much in advance!

Best Regards
Nan Xiao

**Comment by MarkCRay** [comment]
Unfortunately, the Linux kernel is a moving target.   This was introduced in Linux kernel versions 5.7 as documented in the following:

https://lkml.org/lkml/2020/2/21/1269

There are 2 key functions where I need the address, one is the socket fd lookup, and the other is the stack trace save registers.    Both are very important, especially the stack tracing.     I'll see if I can find some other workaround once I get a later kernel installed. 

For now, you can comment out the call to kallsyms_on_each_symbol, however, you will lose the stack tracing ability.

Meanwhile, I'll work on alternatives.

**Comment by NanXiao** [comment]
@MarkCRay Thanks very much for your comments!

**Comment by MarkCRay** [comment]
This is now fixed with LinuxKI version 6.2, which supports Linux kernels through 5.8.14.

Note later kernels may work, but have not been tested at this time.
