### ISSUE TITLE
insmod: ERROR: could not load module likit.ko: No such file or directory

### ISSUE THREAD

**Issue by Schira4396** [HewlettPackard/LinuxKI#40]
why? ubuntu,centos and kali all fail

**Comment by MarkCRay** [comment]
Please refer to the LinuxKI FAQ, which documents a couple of instances for "No such file or directory".  See Q5, Q9, and Q16.    If the installation failed to compile the likit.ko module, then it would not be found.     If none of those apply, please provide more details on exactly what commands you issued the complete list of messages.

**Comment by MarkCRay** [comment]
Have not heard back on over a month.   Will proceed to close out this issue.
