### ISSUE TITLE
Oracle Linux UEK

### ISSUE THREAD

**Issue by devisbal** [HewlettPackard/LinuxKI#46]
During the rpm Install the likit.ko gives an error.
insmod: ERROR: could not load module likit.ko: No such file or directory
Having kernel-uek-devel installed.

But if we do the procedure:
        cd /opt/linuxki
        rm -f /opt/linuxki/modules/likit.ko*
        /opt/linuxki/module_prep
The likit.ko get installed

So it seems there is a different procedure on rpm install VS  /opt/linuxki/module_prep

**Comment by MarkCRay** [comment]
Thank you for reporting the issue.    Can you provide the following output:

uname -a

cat /etc/*release

**Comment by MarkCRay** [comment]
Note also that the /opt/linuxki/linuxki_install script simply does the following:

#
# Configure/install LiKI module
#
rm /opt/linuxki/modules/likit.ko.`uname -r` >/dev/null 2>&1
/opt/linuxki/module_prep

**Comment by devisbal** [comment]
Hello Mark:
The info you requested and results of the process

[root@dbhist19c ~]# uname -a
Linux dbhist19c 5.4.17-2136.302.6.1.el7uek.x86_64 #2 SMP Tue Dec 14 13:21:01 PST 2021 x86_64 x86_64 x86_64 GNU/Linux
[root@dbhist19c ~]# cat /etc/*release
Oracle Linux Server release 7.9
NAME="Oracle Linux Server"
VERSION="7.9"
ID="ol"
ID_LIKE="fedora"
VARIANT="Server"
VARIANT_ID="server"
VERSION_ID="7.9"
PRETTY_NAME="Oracle Linux Server 7.9"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:oracle:linux:7:9:server"
HOME_URL="https://linux.oracle.com/"
BUG_REPORT_URL="https://bugzilla.oracle.com/"

ORACLE_BUGZILLA_PRODUCT="Oracle Linux 7"
ORACLE_BUGZILLA_PRODUCT_VERSION=7.9
ORACLE_SUPPORT_PRODUCT="Oracle Linux"
ORACLE_SUPPORT_PRODUCT_VERSION=7.9
Red Hat Enterprise Linux Server release 7.9 (Maipo)
Oracle Linux Server release 7.9
[root@dbhist19c ~]# rpm --install --nodeps linuxki-7.3-1.noarch.rpm
        Finishing installation of the Linux KI Toolset ...
        Unable to find compatible module - attempting to build from source ...
hostkernel=5.4.17-2136.302.6.1.el7uek.x86_64
hostdistro=ol
hostversion=7.9
EXTRA_CFLAGS=-g -O3 -Wall -DHARDCLOCK_STACK_SKIP=0 -DOTHER_STACK_SKIP=2
make -C /lib/modules/5.4.17-2136.302.6.1.el7uek.x86_64/build  M=/tmp/tmp.YXmXgqTYfB   modules
make[1]: Entering directory `/usr/src/kernels/5.4.17-2136.302.6.1.el7uek.x86_64'
hostkernel=5.4.17-2136.302.6.1.el7uek.x86_64
hostdistro=ol
hostversion=7.9
EXTRA_CFLAGS=-g -O3 -Wall -DHARDCLOCK_STACK_SKIP=0 -DOTHER_STACK_SKIP=2
Building with KERNELRELEASE = 5.4.17-2136.302.6.1.el7uek.x86_64
  CC [M]  /tmp/tmp.YXmXgqTYfB/likit.o
hostkernel=5.4.17-2136.302.6.1.el7uek.x86_64
hostdistro=ol
hostversion=7.9
EXTRA_CFLAGS=-g -O3 -Wall -DHARDCLOCK_STACK_SKIP=0 -DOTHER_STACK_SKIP=2
Building with KERNELRELEASE = 5.4.17-2136.302.6.1.el7uek.x86_64
  Building modules, stage 2.
  MODPOST 1 modules
  CC [M]  /tmp/tmp.YXmXgqTYfB/likit.mod.o
  CTF
  LD [M]  /tmp/tmp.YXmXgqTYfB/likit.ko
make[1]: Leaving directory `/usr/src/kernels/5.4.17-2136.302.6.1.el7uek.x86_64'
cp likit.ko likit.ko.5.4.17-2136.302.6.1.el7uek.x86_64
insmod: ERROR: could not insert module likit.ko: Permission denied

ERROR: Unable to build compatible LiKI module
Please checked to be sure you have the proper kernel headers package installed
and it matches your current kernel version!

After installing the proper kernel header package,
you can build the LiKI DLKM as follows:

        cd /opt/linuxki
        rm -f /opt/linuxki/modules/likit.ko*
        /opt/linuxki/module_prep

You may still be able to use LinuxKI with ftrace mode:

        runki -f

[root@dbhist19c ~]# cd /opt/linuxki
[root@dbhist19c linuxki]# rm -f /opt/linuxki/modules/likit.ko*
[root@dbhist19c linuxki]# /opt/linuxki/module_prep
        Unable to find compatible module - attempting to build from source ...
hostkernel=5.4.17-2136.302.6.1.el7uek.x86_64
hostdistro=ol
hostversion=7.9
EXTRA_CFLAGS=-g -O3 -Wall -DHARDCLOCK_STACK_SKIP=0 -DOTHER_STACK_SKIP=2
make -C /lib/modules/5.4.17-2136.302.6.1.el7uek.x86_64/build  M=/tmp/tmp.1l6fGs7S46   modules
make[1]: Entering directory `/usr/src/kernels/5.4.17-2136.302.6.1.el7uek.x86_64'
hostkernel=5.4.17-2136.302.6.1.el7uek.x86_64
hostdistro=ol
hostversion=7.9
EXTRA_CFLAGS=-g -O3 -Wall -DHARDCLOCK_STACK_SKIP=0 -DOTHER_STACK_SKIP=2
Building with KERNELRELEASE = 5.4.17-2136.302.6.1.el7uek.x86_64
  CC [M]  /tmp/tmp.1l6fGs7S46/likit.o
hostkernel=5.4.17-2136.302.6.1.el7uek.x86_64
hostdistro=ol
hostversion=7.9
EXTRA_CFLAGS=-g -O3 -Wall -DHARDCLOCK_STACK_SKIP=0 -DOTHER_STACK_SKIP=2
Building with KERNELRELEASE = 5.4.17-2136.302.6.1.el7uek.x86_64
  Building modules, stage 2.
  MODPOST 1 modules
  CC [M]  /tmp/tmp.1l6fGs7S46/likit.mod.o
  CTF
  LD [M]  /tmp/tmp.1l6fGs7S46/likit.ko
make[1]: Leaving directory `/usr/src/kernels/5.4.17-2136.302.6.1.el7uek.x86_64'
cp likit.ko likit.ko.5.4.17-2136.302.6.1.el7uek.x86_64
        Compiled compatible LiKI module successfully
        Running depmod - this might take a moment or two ...
[root@dbhist19c linuxki]#

**Comment by MarkCRay** [comment]
Can you check to see if selinux is enabled?    There was a change made some time back where the insmod would give permission denied when installing an external DLKM.    If you search " insmod permission denied selinux" you will find a variety of articles.    If selinux is enabled, try to disable selinux, or you can use the workaround of running the module_prep command as you have done already.

**Comment by devisbal** [comment]
Yes, selinux is enable:
# sestatus
SELinux status:                 enabled
SELinuxfs mount:                /sys/fs/selinux
SELinux root directory:         /etc/selinux
Loaded policy name:             targeted
Current mode:                   enforcing
Mode from config file:          disabled
Policy MLS status:              enabled
Policy deny_unknown status:     allowed
Max kernel policy version:      31

type=AVC msg=audit(1640788977.669:198): avc:  **denied**  { module_load } for  pid=4677 comm="insmod" path="**/tmp/tmp.YXmXgqTYfB/likit.ko**" dev="dm-7" ino=50331791 scontext=unconfined_u:unconfined_r:insmod_t:s0-s0:c0.c1023 tcontext=unconfined_u:object_r:rpm_script_tmp_t:s0 tclass=system permissive=0

Workaround work.
What is the difference between install and de workaround? Since it still is created with selinux enabled?
Can the workaround solution be implemented on install?

**Comment by MarkCRay** [comment]
The difference is due to executing the module_prep script from rpm/yum or executing directly.    With SELinux, the likit.ko module will fail the install if it hasn't been tagged as a module.   Since the DLKM is generated from source, I cannot tag it ahead of time.   However, I tested adding "chcon -t modules_object_t likit.ko" to tag the file as a module and added it to the module_prep script.   If SELinux is not installed or not enabled, then chcon will silently fail, otherwise it will be marked as an object.  

I'll roll this fix into the next release of LinuxKI.   Until then, you'll need to use the workaround of executing the module_prep script separately or disabling SELinux.   

Thanks for pointing this out.   It made me dig a little deeper as to why the insmod was failing!

**Comment by devisbal** [comment]
Thanks Mark.
I'm glad that you found the solution.
Will keep using the workaround until nex version.

**Comment by MarkCRay** [comment]
Fixed in LinuxKI 7.4
