### ISSUE TITLE
ched_setscheduler(): Operation not permitted

### ISSUE THREAD

**Issue by devisbal** [HewlettPackard/LinuxKI#47]
# /opt/linuxki/kiinfo -kidsk
Command line: /opt/linuxki/kiinfo -kidsk

kiinfo (7.3)

sched_setscheduler(): Operation not permitted
failed to make per-CPU threads realtime (possible due to selinux being enabled)
sched_setscheduler(): Operation not permitted
failed to make per-CPU threads realtime (possible due to selinux being enabled)

# cat /etc/redhat-release
Red Hat Enterprise Linux release 8.5 (Ootpa)

# uname -a
Linux genesis 4.18.0-348.12.2.el8_5.x86_64 #1 SMP Mon Jan 17 07:06:06 EST 2022 x86_64 x86_64 x86_64 GNU/Linux

# getenforce
Disabled

**Comment by standamo** [comment]
This is not a bug of kiinfo but a feature of RHEL. The sched_setscheduler() failing with EPERM tells you that there is no available real-time quanta left for kiinfo to use.
See https://access.redhat.com/articles/3696121

**Comment by MarkCRay** [comment]
Thanks for the feedback.  I'll update the error message to include the referenced note in the next release of LinuxKI.

By the way, while sched_setscheduler() failed, it only means that LinuxKI will use real-time priority for the collection deaemons, but it will still work.   It may lose events if it is unable to get sufficient CPU resources if the system is very busy.

**Comment by devisbal** [comment]
Additional info I just detected:
Problem been caused by: "tuned-adm profile throughput-performance"
Removing this profile, resolve the issue, but it require reboot.
Have not yet analyzed which parameter it changes that results in:
sched_setscheduler(): Operation not permitted
failed to make per-CPU threads realtime (possible due to selinux being enabled)
On all cases, selinux is not enable.

**Comment by MarkCRay** [comment]
Additional error information added in LinuxKI version 7.4
