### ISSUE TITLE
error: ‘struct task_struct’ has no member named ‘state’; did you mean ‘__state’?

### ISSUE THREAD

**Issue by devisbal** [HewlettPackard/LinuxKI#48]
hostkernel=4.18.0-372.9.1.el8.x86_64
hostdistro=rhel
hostversion=8.6
EXTRA_CFLAGS=-g -O3 -Wall -DRHEL82 -DHARDCLOCK_STACK_SKIP=8 -DOTHER_STACK_SKIP=2
make -C /lib/modules/4.18.0-372.9.1.el8.x86_64/build  M=/tmp/tmp.aHlmEJ55Wh   modules
make[1]: Entering directory '/usr/src/kernels/4.18.0-372.9.1.el8.x86_64'
hostkernel=4.18.0-372.9.1.el8.x86_64
hostdistro=rhel
hostversion=8.6
EXTRA_CFLAGS=-g -O3 -Wall -DRHEL82 -DHARDCLOCK_STACK_SKIP=8 -DOTHER_STACK_SKIP=2
Building with KERNELRELEASE = 4.18.0-372.9.1.el8.x86_64
  CC [M]  /tmp/tmp.aHlmEJ55Wh/likit.o
/tmp/tmp.aHlmEJ55Wh/likit.c: In function ‘sched_switch_trace’:
/tmp/tmp.aHlmEJ55Wh/likit.c:2458:21: error: ‘struct task_struct’ has no member named ‘state’; did you mean ‘__state’?
  t->prev_state = p->state;
                     ^~~~~
                     __state
make[2]: *** [scripts/Makefile.build:322: /tmp/tmp.aHlmEJ55Wh/likit.o] Error 1
make[1]: *** [Makefile:1577: _module_/tmp/tmp.aHlmEJ55Wh] Error 2
make[1]: Leaving directory '/usr/src/kernels/4.18.0-372.9.1.el8.x86_64'
make: *** [Makefile:229: build] Error 2
insmod: ERROR: could not load module likit.ko: No such file or directory

ERROR: Unable to build compatible LiKI module
Please checked to be sure you have the proper kernel headers package installed
and it matches your current kernel version!

**Comment by MarkCRay** [comment]
Thanks for reporting thing.    I had not yet tested with RHEL 8.6.    The main Linux branch renamed the field to __state in the 5.14 kernel.   While RHEL 8.6 is based on 4.18, they did make changes to this in their code branch.    

0718         RH_KABI_REPLACE_SPLIT(volatile long     state,
0719                               unsigned int      __state
0720 #ifdef CONFIG_PREEMPT_RT
0721         /* saved state for "spinlock sleepers" */
0722                              ,unsigned int      saved_state
0723 #endif
0724                              )

As a workaround, you can modify likit.c to remove the ifdev below and just keep the reference to p->__state.   

#if LINUX_VERSION_CODE < KERNEL_VERSION(5,14,0)
        t->prev_state = p->state;
#else
        t->prev_state = p->__state;
#endif

I'll fix it in the next release.

**Comment by MarkCRay** [comment]
THere are other changes that need to be made to be made to support RHEL 8.6, as just the one change mentioned earlier will allow it to compile, but the system will crash when you start tracing.   I have it fixed, and will be testing RHEL 8.6 along with RHEL 9.0.

**Comment by MarkCRay** [comment]
You may have missed my previous comment "THere are other changes that need to be made to be made to support RHEL 8.6, as just the one change mentioned earlier will allow it to compile, but the system will crash when you start tracing. I have it fixed, and will be testing RHEL 8.6 along with RHEL 9.0.".     I don't believe the message you got is related to crash, but may occur on small memory VMs with low contiguous memory for one or more cpus.  Still there is a coredump issue that I have fixed.    I can sent you a test version if you send your email to "mark.ray@hpe.com".

**Comment by MarkCRay** [comment]
Support for RHEL 8.6 and RHEL 9.0 was added in LinuxKI version 7.4.
