### ISSUE TITLE
likit.o: warning: objtool

### ISSUE THREAD

**Issue by devisbal** [HewlettPackard/LinuxKI#49]
hostkernel=4.18.0-372.26.1.el8_6.x86_64
hostdistro=rhel
hostversion=8.6
EXTRA_CFLAGS=-g -O3 -Wall -DRHEL86 -DHARDCLOCK_STACK_SKIP=8 -DOTHER_STACK_SKIP=2
Building with KERNELRELEASE = 4.18.0-372.26.1.el8_6.x86_64
  CC [M]  /tmp/tmp.vXxPcLzG7j/likit.o
/tmp/tmp.vXxPcLzG7j/.tmp_likit.o: warning: objtool: enable_msr()+0x8f: sibling call from callable instruction with modified stack frame
/tmp/tmp.vXxPcLzG7j/.tmp_likit.o: warning: objtool: block_rq_issue_trace()+0x21: sibling call from callable instruction with modified stack frame
/tmp/tmp.vXxPcLzG7j/.tmp_likit.o: warning: objtool: change_installed_traces()+0x16c: sibling call from callable instruction with modified stack frame
/tmp/tmp.vXxPcLzG7j/.tmp_likit.o: warning: objtool: cpu_buf_read.part.0.isra.0()+0x395: sibling call from callable instruction with modified stack frame
/tmp/tmp.vXxPcLzG7j/.tmp_likit.o: warning: objtool: syscall_exit_trace()+0x12c9: sibling call from callable instruction with modified stack frame
/tmp/tmp.vXxPcLzG7j/.tmp_likit.o: warning: objtool: init_trace_state()+0x162: sibling call from callable instruction with modified stack frame
/tmp/tmp.vXxPcLzG7j/.tmp_likit.o: warning: objtool: block_rq_issue_trace.cold()+0xf: sibling call from callable instruction with modified stack frame

**Comment by MarkCRay** [comment]
Interesting.  I had compiled previously with RHEL 8.6 kernel version 4.18.0-372.9 and had no issues.     Looks like these are Warnings, so I assume the compile completed without ERROR??

Looks like a common problem with more recent GCC versions.   Can you share the gcc version that you used?

**Comment by MarkCRay** [comment]
Can you get gcc -v output so we can identify the version.     

Can you also do the following "/usr/bin/gcc -v" and see if that's different.   You may be using a different GCC version.  

Note that this is not a LinuxKI issue, but a compiler issue.

**Comment by MarkCRay** [comment]
Closing as this is not a LinuxKI issue, but an issue with the version of gcc used.
