### ISSUE TITLE
Feature request: add DKMS support

### ISSUE THREAD

**Issue by cvoltz** [HewlettPackard/LinuxKI#5]
Since LinuxKI uses a kernel module and it needs to be rebuilt whenever the kernel is updated, it should support [DKMS](https://github.com/dell/dkms) so the module can automatically be rebuilt when a new kernel is installed. Unfortunately, while it is actually relatively easy to create the required configuration file, it isn't well documented.

Here are some useful links:
* [DKMS source repository](https://github.com/dell/dkms)
* [Sample DKMS configuration](https://github.com/dell/dkms/blob/master/sample.conf)
* [Sample RPM specification using DKMS](https://github.com/dell/dkms/blob/master/sample.spec)
* [Dynamic Kernel Module Support](https://wiki.archlinux.org/index.php/Dynamic_Kernel_Module_Support) documentation for Arch Linux
* CentOS HowTos [Build Your Own Kernel Modules, Section 2: Building a kernel module using Dynamic Kernel Module Support (DKMS)](https://wiki.centos.org/HowTos/BuildingKernelModules#head-d313bd351f90d4f25a2143b7bbcff73f927731f0)
* [Kernel Korner - Exploring Dynamic Kernel Module Support (DKMS)](http://www.linuxjournal.com/article/6896?page=0,0)

**Comment by MarkCRay** [comment]
Hi Christopher,

Thank you for your request.   It will take me some time to look into this
as I haven't given it much thought in the past.

Mark

On Tue, Sep 12, 2017 at 1:56 PM, Christopher Voltz <notifications@github.com

**Comment by MarkCRay** [comment]
I have made some changes so that if the likit.ko module fails to install, an attempt will be made to automatically re-compile.   I've also added documentation on how to recompile if needed.   For example:
 
    $ cd /opt/linuxki/modules
    $ rm likit.ko*
    $ ../module_prep
