### ISSUE TITLE
Not really a BUG: Skipping BTF generation for /tmp/../likit.ko due to unavailability of vmlinux

### ISSUE THREAD

**Issue by devisbal** [HewlettPackard/LinuxKI#50]
Linux rhel9 5.14.0-70.26.1.el9_0.x86_64 

The BTF stuff is new in RHEL 9.
The kernel config file now has CONFIG_DEBUG_INFO_BTF_MODULES enabled.
With this option set, module build process checks to see if vmlinux is available.
And if not, the "Skipping BTF generation ..." message is displayed.

**Comment by MarkCRay** [comment]
This is not a bug in LinuxKI.
