### ISSUE TITLE
Linux KI 5.3.1 error in redhat 5.8

### ISSUE THREAD

**Issue by vamsi437** [HewlettPackard/LinuxKI#6]
# rpm  --install –nodeps linuxki-5.3-1.noarch.rpm
Or 
#rpm –ivh –nodeps –force linuxki-5.3-1.noarch.rpm
But in both the option getting below error:- 
Error: unpack aging of Archive failed : cpio: Bad Magic

**Comment by CraigOGilmore** [comment]
If I understand correctly, installing the 5.3 version of Linux KI on a RedHat 5.8 system?  The documentation for LinuxKI 5.3 states it is for a system with a 2.6.32-xx kernel version, or later, installed?  My read of RedHat 5.8 documentation says that the 2.6.18-308 is the kernel used, am I reading that incorrectly?

**Comment by MarkCRay** [comment]
Hi Craig, vamsi437,

The documentation is clear that its only supported on 2.6.32 (RHEL 6.0 or
later) kernel.   Be sure to refer to the LinuxKI Masterclass documentation
as well as the LinuxKI FAQ, both of which are on github.

While not supported on 2.6.18 kernels, I am surprised at the type of effort
received.  I wouldn't expect the cpio to fail.   At any rate, be sure you
are using LinuxKI on 2.6.32 or later kernels.

Best Regards,

Mark

**Comment by MarkCRay** [comment]
LinuxKI is only supported on 2.6.32 kernels or later.
