### ISSUE TITLE
Thread names limited to 15 char?

### ISSUE THREAD

**Issue by Pitterling** [HewlettPackard/LinuxKI#61]
seems like thread names are limited to 15char .. 

hdbindexserver (FlushResourcesT) 
hdbindexserver  (SubmitThread-DA)
hdbindexserver  (SubmitThread-LO)

Any option to overcome this limitation? I mean is this just a display issue or is it already collected with the 15c limitation?

Thanks

**Comment by MarkCRay** [comment]
This is a kernel limitation.   From sched.h

/* Task command name length: */
#define [TASK_COMM_LEN]                   16

Then in the task_struct, we can see the following definition:

char                            comm[TASK_COMM_LEN];

See the manpage for "pthread_setname_np" for more information as well, which documents the following:

 The thread name is a meaningful C language string, whose
       length is restricted to 16 characters, including the terminating  null  byte  ('\0').
