### ISSUE TITLE
kiall may hang after merging ki.bin files

### ISSUE THREAD

**Issue by standamo** [HewlettPackard/LinuxKI#62]
After adjusting permissions from the defaults, when I run kiall it hang after line like this:
```
ki.bin files merged by kiinfo -likimerge
```
In process list I see `kiall` with one child: `rm ki.bin.... ki.bin... ...`

IMHO, the problem is that this line may get interactive:
`rm ki.bin.*.$tag  >/dev/null 2>&1`
I think it should be:
`rm -f ki.bin.*.$tag  >/dev/null 2>&1`

**Comment by MarkCRay** [comment]
Fixed in version 7.8, released on Nov 9, 2023.
