### ISSUE TITLE
kiall - spell error "budle" --> "bundle"

### ISSUE THREAD

**Issue by PeterPitterling** [HewlettPackard/LinuxKI#63]
printf "            -t <timestamp>   Only process KI budle with matching timestamp\n"

https://github.com/HewlettPackard/LinuxKI/blob/1d07bd97845a432d425a85b5d509ce8aa449eef6/scripts/kiall#L133
https://github.com/HewlettPackard/LinuxKI/blob/1d07bd97845a432d425a85b5d509ce8aa449eef6/experimental/vis/kiall.pk#L97

**Comment by MarkCRay** [comment]
Thanks.  Will be corrected in the 7.8 version.

**Comment by MarkCRay** [comment]
Fixed in version 7.8, released on Nov 9, 2023.
