### ISSUE TITLE
https://github.com/HewlettPackard/LinuxKI/releases - not listing 7.8 ?

### ISSUE THREAD

**Issue by PeterPitterling** [HewlettPackard/LinuxKI#65]

**Comment by MarkCRay** [comment]
The Releases page does show Release 7.8, but its not at the top.   Instead, its on Page 3.  I'm not quite sure why or how to get it to the top.   The source files show a date of June 25, 2018.  Again, not sure why and I cannot change it.     

You can also get to the 7.8-1 release using this link:  https://github.com/HewlettPackard/LinuxKI/releases/tag/7.8-1.

**Comment by PeterPitterling** [comment]
weird

https://github.com/HewlettPackard/LinuxKI/tree/7.8-1

also pointing to 2018..

**Comment by PeterPitterling** [comment]
you could try resetting the last commit data

`git commit --amend --reset-author --no-edit`

**Comment by MarkCRay** [comment]
Thanks Peter.   That git commit didn't help.   I did find some files in the directory with the 2018 date.  Not sure how it got that way.   I had touch the files, delete the release and delete the tag, and then create a new tag and release.   Release 7.8 is now showing as the latest release at the top of the Releases page.
