### ISSUE TITLE
What exactly does doublebusy mean?

### ISSUE THREAD

**Issue by choijunwoo** [HewlettPackard/LinuxKI#67]
Hi. first, I'm sorry for using a translator because my English is bad 😢

I am checking how hyperthreads affect application performance.

And when using linuxki, I found a doublebusy metric in hyperthread usage.

From what I understand, doublebusy means when threads are stalled at the same time due to CPU backend bound. Is this correct?

My teammate claims that hyperthreads should not be used if this value is higher than 50% (probably considering cache miss situations), but my opinion is that doublebusy has nothing to do with hyperthreads and that you need to check ipc and backend bound.

Could you please give me the right guide?

<img width="824" alt="image" src="https://github.com/HewlettPackard/LinuxKI/assets/6015918/cc089d5f-c21c-4ca0-9855-edac172d9699">

**Comment by MarkCRay** [comment]
Please see section 7.7 of the [LinuxKI MasterClass](https://github.com/HewlettPackard/LinuxKI/raw/master/documentation/LinuxKI_MasterClass.pdf), which describes the Hyperthread statistics in more details.

Let me know if you have any questions.

**Comment by choijunwoo** [comment]
@MarkCRay 
Thanks. I read the code and found out that just double busy when the status of both LCPUs is busy, not the frontend and backend of the core.

> My teammate claims that hyperthreads should not be used if this value is higher than 50% (probably considering cache miss situations), but my opinion is that doublebusy has nothing to do with hyperthreads and that you need to check ipc and backend bound.

Do you know the answer to this?

**Comment by choijunwoo** [comment]
Oh, what I was curious about was whether hyperthreading had a negative effect on application performance when doublebusy was high.

As my teammate said, can this be an absolute indicator?

**Comment by MarkCRay** [comment]
Yes, HT can have a impact, both negative and positive.   It can have a negative impact on latency, meaning one thread can take longer to run if another thread is running at the same time on the HT sibling logical CPU (doublebusy).  However, it can have a positive impact on overall CPU capacity as the physical core can make use of processing stalls (such as memory stalls, etc.) to run another thread on the HT sibling core.
