### ISSUE TITLE
A typo in LinuxKI_QuickRefGuide.pdf

### ISSUE THREAD

**Issue by NanXiao** [HewlettPackard/LinuxKI#68]
In [LinuxKI_QuickRefGuide.pdf](https://github.com/HewlettPackard/LinuxKI/blob/master/documentation/LinuxKI_QuickRefGuide.pdf):

```
Collect with Avanced CPU statistics
runki -R
```

It should be "Advanced", not "Avanced", thanks!

**Comment by MarkCRay** [comment]
Thank you.   This will be fixed in the next release after 7.9.
