### ISSUE TITLE
Make packages available on the releases page and tag releases

### ISSUE THREAD

**Issue by cvoltz** [HewlettPackard/LinuxKI#7]
It is great the `README.md` has links to the latest RPM and APT packages but that requires you to update the file every time you do a release and to add the packages into the source code repository (which is unusual). GitHub projects usually make release files (like RPMs or source tarballs) available on the [Releases](https://github.com/HewlettPackard/LinuxKI/releases) page and don't check them into the repository. The releases page also allows one to include notes such as what has been added, removed, and modified to highlight changes so users can decide if it makes sense to upgrade to a newer release. It also provides a history of releases and allows users to download older releases if needed. 

Information on how to create releases in GitHub is available at:
* [About releases](https://help.github.com/articles/about-releases)
* [Creating releases](https://help.github.com/articles/creating-releases) 

It is also a common practice to tag releases with a version number. If tags are created, making releases is very simple. Information on creating tags in `git` is available [here](https://git-scm.com/book/en/v2/Git-Basics-Tagging).

[ZFS on LInux](https://github.com/zfsonlinux/zfs/releases) is a good example of a project using tags and releases (take a look at the 0.7.0 release to see how new functionality is documented).

**Comment by MarkCRay** [comment]
Thanks for your suggestion Christopher.   I've added tags and the releases page.  I still have a couple of things to clean up with the documentation on the WiKI, but I'll get to that soon.
