### ISSUE TITLE
How to resolve the application's function names?

### ISSUE THREAD

**Issue by NanXiao** [HewlettPackard/LinuxKI#73]
Hello LinuxKI community,

Greetings from me, I am just wondering whether it is possible to resolve the applications' function name. E.g., in following `PID` analysis:

```
    ......
    Process Sleep stack traces (sort by % of total wait time) - Top 20 stack traces
       count    wpct      avg   Stack trace
                  %     msecs
    ===============================================================
       31813 100.00     0.558   do_nanosleep  hrtimer_nanosleep  __x64_sys_nanosleep  do_syscall_64  entry_SYSCALL_64_after_hwframe  |  nanosleep  unknown

    ******** CPU ACTIVITY REPORT ********
    The percentages below reflect the percentage 
    of the Thread's total RunTime spent in either
    User code or System code 
    RunTime:   2.1121

      Count    USER     SYS    INTR
        174     160      14       0
              91.95%   8.05%   0.00%

    HARDCLOCK entries
       Count     Pct  State  Function
         153  87.93%  USER   UNKNOWN
           4   2.30%  SYS    finish_task_switch
           3   1.72%  SYS    syscall_enter_trace
           2   1.15%  USER   nanosleep [/usr/lib64/libpthread-2.28.so]
           2   1.15%  SYS    audit_filter_syscall
           1   0.57%  SYS    __audit_syscall_exit
           1   0.57%  SYS    _raw_spin_unlock_irqrestore
           1   0.57%  USER   __memmove_avx_unaligned_erms_rtm [/usr/lib64/libc-2.28.so]
           1   0.57%  USER   __tls_get_addr [/usr/lib64/ld-2.28.so]
           1   0.57%  USER   __vsprintf_chk [/usr/lib64/libc-2.28.so]
           1   0.57%  USER   pthread_spin_lock [/usr/lib64/libpthread-2.28.so]
           1   0.57%  USER   __strlen_avx2_rtm [/usr/lib64/libc-2.28.so]
           1   0.57%  SYS    hrtimer_nanosleep
           1   0.57%  SYS    audit_reset_context.part.16
           1   0.57%  SYS    audit_filter_inodes

       Count     Pct  HARDCLOCK Stack trace
       ============================================================
           4   2.30%  finish_task_switch  __schedule  schedule  do_nanosleep  hrtimer_nanosleep  __x64_sys_nanosleep  do_syscall_64  entry_SYSCALL_64_after_hwframe  |  nanosleep  unknown  unknown
           3   1.72%  syscall_enter_trace  syscall_trace_enter  do_syscall_64  entry_SYSCALL_64_after_hwframe  |  nanosleep  unknown  unknown
           2   1.15%  audit_filter_syscall  __audit_syscall_exit  syscall_slow_exit_work  do_syscall_64  entry_SYSCALL_64_after_hwframe  |  nanosleep  unknown  unknown
           1   0.57%  _raw_spin_unlock_irqrestore  hrtimer_start_range_ns  do_nanosleep  hrtimer_nanosleep  __x64_sys_nanosleep  do_syscall_64  entry_SYSCALL_64_after_hwframe  |  nanosleep  unknown  unknown
           1   0.57%  hrtimer_nanosleep  __x64_sys_nanosleep  do_syscall_64  entry_SYSCALL_64_after_hwframe  |  nanosleep  unknown  unknown
           1   0.57%  audit_reset_context.part.16  syscall_slow_exit_work  do_syscall_64  entry_SYSCALL_64_after_hwframe  |  nanosleep  unknown  unknown
           1   0.57%  __audit_syscall_exit  syscall_slow_exit_work  do_syscall_64  entry_SYSCALL_64_after_hwframe  |  nanosleep  unknown  unknown
           1   0.57%  audit_filter_inodes  __audit_syscall_exit  syscall_slow_exit_work  do_syscall_64  entry_SYSCALL_64_after_hwframe  |  nanosleep  unknown  unknown
    ......
```

You can see all application's functions' names are "`unknown`". I have installed the `debuginfo` package of the application, but seems no use. Any idea about this issue? Thanks very much in advance!

Best Regards
Nan Xiao

**Comment by MarkCRay** [comment]
There are a few reasons why LinuxKI cannot translate the USER hex address into a symbol name. 

- The binary or library has been stripped
- The process/thread is running in a container
- The process/thread dies before the runki script is done, so we cannot identify the binary/library name used by the dead process/thread.

Remember, that LinuxKI does a binary dump of the trace data.   It doesn't know at the time the trace data is collected whether the binary or library is stripped or whether the thread is running in a container.   It has to collect the debug data from the binaries and libraries AFTER the trace data is collected, and it has no wait to know where the debuginfo files if the file is stripped, or which binary or library was used if the thread dies during the trace. 

For the 1st two situations above, you can manually drop the debug file into the objdump directory, but it must be for the exact same version of the binary that was running when the LinuxKI data was captured.    Below are more detailed instructions to follow:

You can look at the KI ASCII trace file for the binary/library name if it was available.   You should see a record such as:

`    4.997257 cpu=14 pid=55042 tgid=55042 hardclock state=USER 0x7ffe605c6cd5  [mark.strip]:0x4008ef  [libc-2.17.so]:__libc_start_main+0xf5`

Note that I specifically used the mark.strip binary.    You can get the full pathname from maps file:

`$ grep "mark.strip" maps.1106_0841`
`00400000-00401000 r-xp 00000000 fd:0d 993339                /home/mcr/source/mark.strip`
`00600000-00601000 r--p 00000000 fd:0d 993339                /home/mcr/source/mark.strip`
`00601000-00602000 rw-p 00001000 fd:0d 993339                /home/mcr/source/mark.strip`

If you have the debug symbols, you can copy it to the the objdumps.<timestamp> file.   For example:

`$ cp mark.debug objdumps.1106_0841/?home?mcr?source?mark.strip`

Note you have to replace the '/' with the '?' in the pathname.    Then simply run kiall again and it should pick up the sysmbols from the debug file.

**Comment by NanXiao** [comment]
@MarkCRay Yes, your method works! BTW, I have one more question, my application uses many 3rd-party libraries, and I still get some `"unknown"` function names. Is there any out-of-box method to know which libraries lack debug info? Or I need to grep in KI ASCII trace file myself? Thanks very much for your time and help in advance!

**Comment by NanXiao** [comment]
@MarkCRay Thanks very much for your time and help!
