### ISSUE TITLE
Question about kiall script's error exit codes

### ISSUE THREAD

**Issue by NanXiao** [HewlettPackard/LinuxKI#75]
Hi LinuxKI community,

In [kiall](https://github.com/HewlettPackard/LinuxKI/blob/be8b924368f22c23cecbbd33f4a8433ad7677fde/scripts/kiall#L594) script:

```
if [ $rflag -eq 1 -a $cflag -eq 1 ] ; then
    echo "ERROR: Cannot use both -r and -c options"
    exit 9
fi

if [ $rflag -eq 1 -a $fflag -eq 1 ] ; then
    echo "ERROR: Cannot use both -r and -f options"
    exit 10 
fi

if [ $cflag -eq 1 -a $fflag -eq 1 ] ; then
    echo "ERROR: Cannot use both -r and -f options"
    exit 10 
fi
```

IMHO, maybe `kiall` should use same error exit code (e.g., `9`), or `3` different error exit code (e.g., `9`, `10`, `11`)? Thanks!

Best Regards
Nan Xiao

**Comment by MarkCRay** [comment]
The last one should be "Cannot use both -c and -f options".  

I'm not sure anyone is really checking the return code, but I'll use a unique return code.

**Comment by NanXiao** [comment]
@MarkCRay Thanks very much for your time and help!
