### ISSUE TITLE
The differences between "multi-system environments" and "cluster"?

### ISSUE THREAD

**Issue by NanXiao** [HewlettPackard/LinuxKI#76]
Hello LinuxKI community,

Sorry for disturbing again! I found `kiall -r` is for "`same system or in multi-system environments`" while `kiall -c` is for "`cluster`". TBH, I don't understand the differences between `multi-system environments` and `cluster`. I tried to google, but unfortunately can't get the answers too. Anybody can explain to me? Thanks very much for your time and help in advance!

Best Regards
Nan Xiao

**Comment by rahulhkulkarni** [comment]
Hi Nan Xiao,

kiall -r option is used to create a <hostname>/<timestamp> ( MMDD_HHMM ) subdirectory structure which can be used to organize multiple trace collections from different hosts.
For example, if you have 8 ki_all.*.tgz files belonging to 4 nodes ( hosts), it will create directories as below -

ki files:
ki_all.node1.1021_1630.tgz
ki_all.node1.1021_1730.tgz
ki_all.node2.1021_1630.tgz
ki_all.node2.1021_1730.tgz
ki_all.node3.1021_1630.tgz
ki_all.node3.1021_1730.tgz
ki_all.node4.1021_1630.tgz
ki_all.node4.1021_1730.tgz

Directories created:

node1/1021_1630/
node1/1021_1730/
node2/1021_1630/
node2/1021_1730/
node3/1021_1630/
node3/1021_1730/
node4/1021_1630/
node4/1021_1730/


If you want to generate kiall reports for a cluster, you need to collect ki traces on all cluster nodes (preferably simultaneously ) and use "kiall -c" to generate reports. "-c" will create subdirectory of the form <timestamp>/<hostname> for each ki_all.*.tgz file found in the current working directory. Note this directory structure is different than one created with kiall -r, which uses the form <hostname>/<timestamp>. When you use "-c" option, other than per node reports for each host, kiall will create cluster overview report (cl.<timestamp>.html) in addition.

For example, consider you have below ki files for 3 cluster nodes -
ki_all.cnode1.0218_0735.tgz 
ki_all.cnode2.0218_0735.tgz 
ki_all.cnode3.0218_0735.tgz

Your output files/directories will be as below. 

$ pwd
/var/linuxki
$ ls
0218_0735
$ ls 0218_0735
cp.0218_0735.html cnode1 cnode2 cnode3 kiall.0218_0735.csv


Please refer section 3.2 and 8.4 of LinuxKI_MasterClass.pdf for more details.

https://github.com/HewlettPackard/LinuxKI/raw/master/documentation/LinuxKI_MasterClass.pdf

Note that, installing linuxki on all nodes of a cluster and collecting data simultaneously can be done using procedure documented in above mentioned LinuxKI_MasterClass.pdf (section 8)

Regards,
Rahul

**Comment by NanXiao** [comment]
@rahulhkulkarni Thanks very much for your time and detailed explanation! I think I get the point:
(1) "multi-system environments" means the hosts are independent;
(2) Cluster means the hosts in the cluster work as a whole, so should be analysed together to generate a cluster overview report.
Is my understanding correct? Thanks very much in advance!

**Comment by rahulhkulkarni** [comment]
Hi Nan Xiao, yes, your understanding is correct.

**Comment by NanXiao** [comment]
@rahulhkulkarni Thanks very much for your quick reply!
